### PR TITLE
V2: Use xplatform for logging

### LINKED ISSUE #4062: `zwe` logging issues
There is a room for `zwe` logging improvement:

## 1) Sometimes it is working
```
rm /logs/*
/zowe/bin/zwe start -c ./zowe.wrong.yaml -l /logs --configmgr
cat /logs/*
Zowe server command: zwe start
- timestamp: 2024-10-30 07:52:21
- parameters:
  * config: ./zowe.wrong.yaml
  * log-dir: /logs
```

## 2) Sometimes not
```
rm /logs/*
/zowe/bin/zwe start -c 'FILE(./zowe.yaml)' -l /logs
cat /logs/*
���������+�!|�ᎎ���?ʀ!��<���� �/�%����?���/�Ȁ!��(��욀������!��(�����<���߀�������߀�+��������������������+����������������������
```

## 3) And in some cases, it is ignoring a lot of errors [solved by #4064 ]
```
/zowe/bin/zwe start -c 'FILE(./zowe.yaml)' -l /logs/zwe-start-20241030T075233.log

mkdir: FSUM6404 directory "/logs/zwe-start-20241030T075233.log": EDC5117I File exists. (errno2=0x053B006C)
touch: file "/logs/zwe-start-20241030T075233.log/zwe-start-20241030T080058.log": EDC5135I Not a directory. (errno2=0x0594003C)
chmod: FSUM6180 file "/logs/zwe-start-20241030T075233.log/zwe-start-20241030T080058.log": EDC5135I Not a directory. (errno2=0x0594003C)
WARNING: cannot write to /logs/zwe-start-20241030T075233.log/zwe-start-20241030T080058.log
...
WARNING: cannot write to /logs/zwe-start-20241030T075233.log/zwe-start-20241030T080058.log
Temporary directory '/tmp/.zweenv-5880' created.
Zowe will remove it on success, but if zwe exits with a non-zero code manual cleanup would be needed.
===============================================================================
ERROR: fileExists path=/logs/zwe-start-20241030T075233.log/zwe-start-20241030T080058.log, err=135
...
ERROR: fileExists path=/logs/zwe-start-20241030T075233.log/zwe-start-20241030T080058.log, err=135
InternalError: stack overflow
    at fileExists (/zowe/bin/libs/fs:205)
    at writeLog (/zowe/bin/libs/common:119)
    at printRawMessage (/zowe/bin/libs/common:157)
    at printError (/zowe/bin/libs/common:166)
...
```

### PR DESCRIPTION
**Pull request by Martin-Zeithaml**
Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [x] Bugfix 

#### Relevant issues

Fixes #4062

#### Does this PR introduce a breaking change?

- [x] No

### CODE REVIEW

File: bin/libs/common.ts [hunk 1]
```diff
@@ -128,36 +128,21 @@ export function date(...args: string[]): string|undefined {
...
-          logFile=null;
-          logExists=false;
-          return false;
-        }
-      }
-    }
-  }
-  if (logFile===undefined || logFile===null) {
-    return false;
   } else {
```
Comment (MarkAckert) [inline bin/libs/common.ts:141]: If the log doesn't exist, we create it and drop the message with this new logic - the `else` is never hit on first pass. Is that intended?

Comment (Martin-Zeithaml) [reply bin/libs/common.ts:141]: I believe, it is ok. We are creating file and initializing it with content of `message`. We have to skip the `else` part, otherwise we will duplicate the first message in the log.

Comment (MarkAckert) [reply bin/libs/common.ts:141]: I see it now, my mistake. Thx!

**Review by MarkAckert — APPROVED** [review]
