### PR TITLE
Users/jack/extended tests sec sys

### LINKED ISSUE #712: Create builds for zowe-install-test on TSS/ACF2
Depends on #711

Fan-out the zowe-install-test build to also run against the TSS and ACF2 LPARs.

- Some tests will not work out of the box
- Security manager commands are the likely reasons for failure
- Investigate where security commands are run
  - ACF2 will require JCL
  - CUPIDS: is JCL the long-term plan for install security commands?

### PR DESCRIPTION
**Pull request by jackjia-ibm**
Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [x] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [ ] Bugfix 
- [x] Feature 
- [ ] Other... Please describe:

#### Relevant issues

Fixes #712, as part of https://github.com/zowe/zowe-install-packaging/issues/1198.

#### Changes proposed in this PR

- Added 3 sets of extended test cases on ACF2/TS servers with testing of convenience build, smpe fmid, smpe ptf.

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Additional Context

The changes are set to running sequentially for now. I decide to leave the complexity of merging test reports to later. The complexities and uncertainties are:

- running smoke test in parallel in same folder will result in the test reports competing updating the same report, we need a way to separate the reports.
- once we have other format of sanity test results (generated by Gradle for example), we will need extra caution to solve the problem when have them running in parallel, and it will also bring much more complexity to combine into one test report.

### CODE REVIEW

**Comment by jackjia-ibm** [comment]
Test https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1294/lastSuccessfulBuild/Report_3a_20Test_20Result/ shows expected result:

- run 3 tests on 3 servers in a row
- displayed test results on 3 test cases

The test is on `zowe-1.10.0-staging-692-20200424170636.pax` which got same result as https://wash.zowe.org:8443/job/zowe-install-test/job/staging/121/. The 2 failed test cases are related to missing workflow app in Desktop.

File: tests/installation/src/__tests__/extented/security-systems/convenience/acf2.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
+/**
```
Comment (stevenhorsman) [inline tests/installation/src/__tests__/extented/security-systems/convenience/acf2.ts:1]: We should maybe fix the typo 'extended' in the directory name next iteration when we have more time
