### PR TITLE
TSS: Detect zOSMF Root CA

### LINKED ISSUE #3362: zwe init certificate command to detect z/OSMF root CA
`zwe init certificate` command fails when tries to detect z/OSMF root CA to add it to the keyring. 
(Certificate setup scenario 4; RACF)

Issue seems to be related to this part of code 
https://github.com/zowe/zowe-install-packaging/blob/v2.x/staging/bin/libs/certificate.sh#L1371

It issues RACDCERT LIST ID(IZUSVR) and then tries to process the output to get the keyring name, but as a result gets an odd line containing names of all keyrings owned by IZUSVR mixed up with field names like "Label", "Certificate", "Status" etc

Then it tries to issue RACDCERT LISTRING for the given line and fails as there is no such keyring:

```
>> Generate Zowe certificate in keyring

- Detect z/OSMF keyring by listing ID(IZUSVR)
  * z/OSMF keyring name is <KEYRING_NAME_1>Ring<KEYRING_NAME_2>Label:CertificateStatus:StartEndSerial05Issuer'sLabel:CertificateStatus:StartEndSerial06Issuer's<KEYRING_NAME_4>
- Detect z/OSMF root certificate authority by listing keyring (<KEYRING_NAME_1>Ring<KEYRING_NAME_2>Label:CertificateStatus:StartEndSerial05Issuer's<KEYRING_NAME_3>Label:CertificateStatus:StartEndSerial06Issuer's<KEYRING_NAME_4>)
  * Exit code: 4
  * Output:
    RACDCERT LISTRING(<KEYRING_NAME_1>Ring<KEYRING_NAME_2>Label:CertificateStatus:StartEndSerial05Issuer's<KEYRING_NAME_3>Label:CertificateStatus:StartEndSerial06Issuer's<KEYRING_NAME_4>) ID(IZUSVR)
    IRRD114I Ring <KEYRING_NAME_1>Ring<KEYRING_NAME_2>Label:CertificateStatus:StartEndSerial05Issuer's<KEYRING_NAME_3>Label:CertificateStatu
    s:StartEndSerial06Issuer's<KEYRING_NAME_4> does not exist.
Error ZWEL0137E: z/OSMF root certificate authority is not provided (or cannot be detected) with trusting z/OSMF option enabled.
```

### PR DESCRIPTION
**Pull request by Martin-Zeithaml**
Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [x] DCO signoffs have been added to all commits, including this PR

#### PR type

- [x] Feature 

#### Relevant issues

Partially fixes #3362 

#### Changes proposed in this PR
`detect_zosmf_root_ca` is currently working only for `RACF`.
I have added functionality for `TSS`.
`ACF2` will be (or not) added in different PR.

#### Does this PR introduce a breaking change?

- [x] No

#### Does this PR do something the person installing Zowe should know about?

You can install Zowe under `TSS` with option `--zosmf-ca _auto_`

#### Other information

ACF2 is not working under `tsocmd`, however there is utility `ACFUNIX` to get very same behavior. Needs to be discussed.

VERSION:2.15.0
CHANGELOG:TSS supported for detection of z/OSMF Root CA.

### CODE REVIEW

**Review by 1000TurquoisePogs — COMMENTED** [review]
So far this looks great. Since it's marked "WIP" i wont approve yet but let me know when you're ready.

**Comment by Martin-Zeithaml** [comment]
I have verified, that `--zosmf-ca _auto_` can be used for `keyring-jcl connect | generate | import-ds`, the change for all `.parameters` files should be ok.
I will do more testing on Monday, let's keep **WIP** there.

File: bin/libs/certificate.sh [hunk 1]
```diff
@@ -1397,12 +1405,76 @@ EOF
...
+  # KEYRING LABEL = KEYRING.IZUDFLT
+  zosmf_keyring_name=$(echo "${zosmf_certs}" | grep "KEYRING LABEL = " | awk -F= '{ print $2 }'  | head -n 1)
+  if [ -n "${zosmf_keyring_name}" ]; then
+    print_trace "  * z/OSMF keyring name is ${zosmf_keyring_name}"
+    # Output example:
+    #   ACID(CERTAUTH)  DIGICERT(ABCDEFGH)  DEFAULT(NO )  USAGE(CERTAUTH)
+    #   LABLCERT(ZOSMF_ROOT_CA                   )
+    zosmf_root_ca=$(echo "${zosmf_certs}" | grep -A 1 "ACID(CERTAUTH)" | grep "LABLCERT(" | head -n 1)
+    zosmf_root_ca=$(echo "${zosmf_root_ca}" | awk '{ print substr( $0, 12, length($0)-13) }')
+    zosmf_root_ca=$(echo "${zosmf_root_ca}" | sed -e 's/^[[:space:]]*//;s/[[:space:]]*$//')
```
Comment (1000TurquoisePogs) [inline bin/libs/certificate.sh:1436]: for the awk command: are you sure this is the right offset? in your above output example where LABLCERT has 3 spaces before, the result because (ZOSMF_ROOT_CA
maybe it has 4 spaces and the example was just missing spaces?
Just double checking on it...


For the sed command: is this just removing whitespace? it's hard to read since i'm only a sed novice. could try `xargs` instead? it trims spaces too.

Comment (Martin-Zeithaml) [reply bin/libs/certificate.sh:1436]: 1) I am automatically placing 1 space after the comment char `#`
```
 # Output example:
    #   ACID(CERTAUTH)  DIGICERT(ABCDEFGH)  DEFAULT(NO )  USAGE(CERTAUTH)
    #   LABLCERT(ZOSMF_ROOT_CA                   )
```
is in output
```
  ACID(CERTAUTH)  DIGICERT(ABCDEFGH)  DEFAULT(NO )  USAGE(CERTAUTH)
  LABLCERT(ZOSMF_ROOT_CA                   )
```

I was testing this with raw output and it seems to work fine.

2) `xargs` explained [here](https://github.com/zowe/zowe-install-packaging/issues/3720). It is working unexpectedly comparing to `trim` from JS or other languages.

Comment (1000TurquoisePogs) [reply bin/libs/certificate.sh:1436]: okay thanks, now i understand it and this comment chain will help others know in the future.

**Review by 1000TurquoisePogs — APPROVED** [review]
